--- 
title: "Immcantation - enchantR"
subtitle: "Single cell qc"
author: ""
date: "Updated: `r date()`"
knit: "bookdown::render_book"
site: bookdown::bookdown_site
documentclass: book
bibliography: "references.bib"
biblio-style: apalike
link-citations: yes
description: "enchantr single cell qc report"
output: enchantr::immcantation
params:
   input: 
      label: "`input`: Path to repertoire file"
      input: file
      value: "scExampleDb.tsv"
   outname:
      label: "`outname`"
      input: text
      value: "scqc"
   log:
      label: "`log`"
      input: text
      value: "command_log"
   outdir:
      label: '`outdir`: Output directory'
      input: text
      value: !r file.path(getwd(),'enchantr')
   date: 
      label: '`date`: Run date'
      input: date
      value: !r format(Sys.time(), "%Y-%m-%d")
   logo:
      label: "`logo`: Path to report logo"
      input: file
      value: !r file.path("assets", "logo.png")
   logolink:
      label: "`logolink`: URL to be added to the logo"
      input: text
      value: "immcantation.org"
   echo: 
      label: '`echo`: Show code in the report.'
      input: checkbox
      value: FALSE
   cache:
      label: '`cache`: Use cached results'
      input: checkbox
      value: FALSE
editor_options: 
  chunk_output_type: inline
---

```{r global-options, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=4, fig.path = "figures/",
                      echo=params$echo,cache=params$cache,
                      warning=FALSE, message=FALSE,
                      eval.after="fig.cap",
                      out_dir=params$outdir,
                      eval.opts = c('eval', 'echo', 'fig.height', 'fig.width'))
library(enchantr)
library(DT)
file.copy(params$logo, 
          file.path(params$outdir,"assets", paste0("logo", gsub(".+(\\..+$)","\\1",params$logo))),
          recursive = T, overwrite=T)
```

# Input parameters

```{r input-parameters}
params
if (!dir.exists(params[['outdir']])) {
   dir.create(params[['outdir']], recursive = T)
}
save(params, file=file.path(params$outdir,"params.RData"))
```

# Read repertoire

```{r}
# Libraries
suppressPackageStartupMessages(library("enchantr"))
suppressPackageStartupMessages(library("DT"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("airr"))
suppressPackageStartupMessages(library("alakazam"))
suppressPackageStartupMessages(library("shazam"))
suppressPackageStartupMessages(library("plotly"))
```

```{r}
# Check input file
if (!file.exists(params$input)) {
    stop(paste0("File ", basename(params$input), " doesn't exist."))
}

# Read metadata file
db <- read_rearrangement(params[['input']])
```

# Distribution of the number of sequences per cell and locus

```{r}
seqs_per_cell <- countSequencesPerCell(db)
```

```{r p-seqs-per-cell, fig.width=8, fig.height=4, fig.cap=p_seqs_per_cell$enchantr$html_caption}
p_seqs_per_cell <- plotSequencesPerCell(seqs_per_cell)
p_seqs_per_cell <- eeplot(p_seqs_per_cell, params$outdir, knitr::opts_current$get('label'))
ggplotly(p_seqs_per_cell)
```

# QC

```{r}
qc_results <-scQC(db)
if (qc_results$fail>0) {
  cells_with_fail <- unique(qc_results$log$cell_id[!qc_results$log$scqc_pass])
}
```

`r qc_results$pass` sequences pass and `r qc_results$fail` sequences fail.

```{r eval=qc_results$fail>0, class.output="bg-warning"}
fail_cell_ids <- unique(qc_results$log$cell_id[!qc_results$log$scqc_pass])
eetable(qc_results$log %>%
          filter(cell_id %in% cells_with_fail),
        caption=paste0("Sequences of ",length(cells_with_fail), " cell_ids with failed sequences."))
```

## Cells with paired chains


```{r}
# TODO: WIP
# ggplot(qc_results$log, aes(x=cell_num_sequences)) +
#         geom_histogram(binwidth = 1) +
#         scale_x_continuous(breaks=1:max(seqs_per_cell$cell_num_sequences)) +
#         facet_wrap(~locus) +
#         labs(
#             x= "Number of sequences in a cell.",
#             y=" Count",
#             caption="Distribution of the number of sequences per cell and locus."
#         )
```

# Save results

```{r dbpass}
pass <- qc_results$log$scqc_pass

if (!is.null(params$outname)) {
    output_fn <- paste0(params$outname,"_scqc-pass.tsv")
} else {
    output_fn <- sub(".tsv$", "_scqc-pass.tsv", basename(params$input))
}

if (!is.null(params$log)) {
    log_fn <- paste0(params$log,".txt")
} else {
    log_fn <- sub("_scqc-pass.tsv$", "_command_log.txt", basename(output_fn))
}

write_rearrangement(db[pass,], file=output_fn)
```

```{r log}
cat("START> SingleCellQC", file=log_fn, append=F)
cat(paste0("\nFILE> ",basename(params$input)), file=log_fn, append=T)
cat(paste0("\nOUTPUT> ",basename(output_fn)), file=log_fn, append=T)
cat(paste0("\nPASS> ",sum(pass)), file=log_fn, append=T)
cat(paste0("\nFAIL> ",sum(!pass)), file=log_fn, append=T)
```

```{r, child=c('versions.Rmd')}
```


