FROM immcantation/enchantr:dev
LABEL maintainer="Gisela Gabernet [gisela.gabernet@yale.edu], \
                  Susanna Marquez [susanna.marquez@yale.edu]" \
description="Full suite of the Immcantation framework tools and dependencies with latest enchantr version."

# Copy enchantr source code
COPY . /tmp/enchantr

# Install enchantr
RUN rinstall -p "/tmp/enchantr" -u never

# Set commands
CMD echo -e " Version information:\n"\
            "  versions report\n"\
            "Build stamps:\n"\
            "  builds report\n"\
            "Description of available pipelines:\n"\
            "  pipelines report"
