--- 
title: "Immcantation - enchantR"
subtitle: "Detect contamination"
author: ""
date: "Updated: `r date()`"
knit: "bookdown::render_book"
site: bookdown::bookdown_site
documentclass: book
bibliography: "references.bib"
biblio-style: apalike
link-citations: yes
description: "detect sequences present in multiple samples"
output: enchantr::immcantation
params:
   input: 
      label:  "`input`: Path to repertoires file(s)"
      input: file
      value: "input_id_1_meta-pass.tsv,input_id_2_meta-pass.tsv,input_id_3_meta-pass.tsv"
   input_id: 
      label: "`input_id`: Name of the column in the data files that contains input identifiers."
      input: text
      value: "id"      
   outname:
      label: "`outname`"
      input: text
      value: "cont"
   log:
      label: "`log`"
      input: text
      value: "command_log"
   outdir:
      label: '`outdir`: Output directory'
      input: text
      value: !r file.path(getwd(),'enchantr')
   date: 
      label: '`date`: Run date'
      input: date
      value: !r format(Sys.time(), "%Y-%m-%d")
   logo:
      label: "`logo`: Path to report logo"
      input: file
      value: !r file.path("assets", "logo.png")
   logolink:
      label: "`logolink`: URL to be added to the logo"
      input: text
      value: "immcantation.org"
   echo: 
      label: '`echo`: Show code in the report.'
      input: checkbox
      value: FALSE
   cache:
      label: '`cache`: Use cached results'
      input: checkbox
      value: FALSE
editor_options: 
  chunk_output_type: inline
---

```{r global-options, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=4, fig.path = "figures/",
                      echo=params$echo,cache=params$cache,
                      warning=FALSE, message=FALSE,
                      eval.after="fig.cap",
                      out_dir=params$outdir,
                      eval.opts = c('eval', 'echo', 'fig.height', 'fig.width'))
# Libraries
suppressPackageStartupMessages(library("enchantr"))
suppressPackageStartupMessages(library("DT"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("airr"))
suppressPackageStartupMessages(library("alakazam"))
suppressPackageStartupMessages(library("shazam"))

file.copy(params$logo, 
          file.path(params$outdir,"assets", paste0("logo", gsub(".+(\\..+$)","\\1",params$logo))),
          recursive = T, overwrite=T)
```

# Input parameters

```{r input-parameters}
params
if (!dir.exists(params[['outdir']])) {
   dir.create(params[['outdir']], recursive = T)
}
save(params, file=file.path(params$outdir,"params.RData"))
```

# Read repertoire


```{r}

# Check input file
if (!file.exists(params$input)) {
    stop(paste0("File ", basename(params$input), " doesn't exist."))
}

db_files <- read.delim(params[['input']], header=F)[[1]]

# Load repertoire file(s)
db <- bind_rows(lapply(db_files, read_rearrangement))
```

# Identify possible contaminants

```{r overlapSeqInHeavy}
db_ovl <- plotDbOverlap(db %>% 
                           dplyr::filter(locus %in% c("IGH", "igh", "TRB", "trb", "TRD", "trd")),
                        group = c("sample_id"), 
                        features=c("sequence_alignment", "junction"),  
                        plot_order=c("sample_id"), 
                        identity=c("ambiguous", "ambiguous"), 
                        similarity = c("min","min"), 
                        title="auto", silent=T)
db_ovl
```

# Summary

```{r summary}
# TODO
# summary <- db %>% group_by(!!rlang::sym(params$input_id)) %>%
#    summarize(n=n())
# eetable(summary, "Number of input sequences and flagged sequences per input sample.")
```

```{r dbpass}
# TODO
# Currently this report is just for FYI
# need to enable the option to remove flagged
pass <- rep(T, nrow(db))

if (!is.null(params$outname)) {
    output_fn <- paste0(params$outname,"_cont-flag.tsv")
} else {
    output_fn <- sub(".tsv$", "_cont-flag.tsv", basename(params$input))
}

if (!is.null(params$log)) {
    log_fn <- paste0(params$log,".txt")
} else {
    log_fn <- sub("_cont-flag.tsv$", "_command_log.txt", basename(output_fn))
}

write_rearrangement(db[pass,], file=output_fn)
```

```{r log}
cat("START> BulkOverlap", file=log_fn, append=F)
cat(paste0("\nFILE> ",basename(params$input)), file=log_fn, append=T)
cat(paste0("\nOUTPUT> ",basename(output_fn)), file=log_fn, append=T)
cat(paste0("\nPASS> ",sum(pass)), file=log_fn, append=T)
cat(paste0("\nFAIL> ",sum(!pass)), file=log_fn, append=T)
```


```{r, child=c('versions.Rmd')}
```


