--- 
title: "Immcantation - enchantR"
subtitle: "Input validation"
author: ""
date: "Updated: `r date()`"
knit: enchantr::render_book
site: bookdown::bookdown_site
documentclass: book
bibliography: "references.bib"
biblio-style: apalike
link-citations: yes
description: "enchantr input validation report"
output: enchantr::immcantation
params:
   input: 
      label: "`input`: Path to input metadata file"
      input: file
      value: "example_airr_metadata.tsv"
   collapseby: 
      label: "`collapseby`: Fields in `input` that group data to collapse duplicated sequences"
      value: 'sample_id'
   cloneby:
      label: "`cloneby`: Fields in `input` that group data to identify groups of clonally related sequences"
      value: 'subject_id'
   reassign: 
      label: '`reassign`: if `input` is a .tsv repertoire, will gene calls be reassigned later in the pipeline?'
      input: checkbox
      value: FALSE
   output: 'validated_input'
   miairr: 
      label: "`miairr`: Path to AIRR standard mapping file."
      input: file
      value: "mapping_MiAIRR_BioSample_v1.3.1.tsv"
   outdir:
      label: '`outdir`: Output directory'
      input: text
      value: !r file.path(getwd(),'enchantr')
   date: 
      label: '`date`: Run date'
      input: date
      value: !r format(Sys.time(), "%Y-%m-%d")
   logo:
      label: "`logo`: Path to report logo"
      input: file
      value: !r file.path("assets", "logo.png")
   logolink:
      label: "`logolink`: URL to be added to the logo"
      input: text
      value: "immcantation.org"
   echo: 
      label: '`echo`: Show code in the report.'
      input: checkbox
      value: TRUE
   cache:
      label: '`cache`: Use cached results'
      input: checkbox
      value: FALSE
editor_options: 
  chunk_output_type: inline
---

```{r global-options, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=4, fig.path = "figures/",
                      echo=params$echo,cache=params$cache,
                      warning=FALSE, message=FALSE,
                      out_dir=params$outdir,
                      eval.opts = c('eval', 'echo', 'fig.height', 'fig.width'))

suppressPackageStartupMessages(library("enchantr"))
suppressPackageStartupMessages(library("DT"))

if (!dir.exists(params[['outdir']])) {
    dir.create(params[['outdir']], recursive = T)
}

file.copy(params$logo, 
          file.path(params$outdir,"assets", "logo.png"),
          recursive = T, overwrite=T)
```

# Input parameters

```{r input-parameters, results='asis'}
printParams(params)
```
```{r echo=FALSE, results='asis'}
print_table_caption(tag="input", text="Input parameters.")
save(params, file=file.path(params$outdir,"params.RData"))
```

# Metadata validation


```{r}
input <- validate_input(input=params[['input']], 
                        miairr=params[['miairr']],
                        collapseby=params[['collapseby']],
                        cloneby=params[['cloneby']],
                        reassign=params[['reassign']])
```

```{r}
# Write validation results to a file
write.table(input$table, file=file.path(params$outdir, paste0(params$output,".tsv")), sep="\t",
            quote=FALSE, row.names = FALSE)

# DT::saveWidget(dt, file=paste0(params$output,".html"))
```

```{r}
check_fields <- c("valid_filename", "valid_species", "valid_collapseby", "valid_cloneby", "valid_single_cell", "valid_pcr_target_locus", "valid_sequence_alignment")
not_valid_rows <- which(rowSums(input$table[, check_fields, drop=FALSE]) < length(check_fields))
```

```{r, error=T}
if (length(not_valid_rows) > 0) {
   write.table(input$table[not_valid_rows,], file=file.path(params$outdir, paste0(params$output,"_not-valid.tsv")), sep="\t",
               quote=FALSE, row.names = FALSE)
   message("Please review your input data. Invalid information found.")
}
```

`r length(not_valid_rows)` invalid rows (row numbers: `r paste(not_valid_rows, collapse=",")`).

```{r}
dt <- DT::datatable(input$table,
              rownames = FALSE,
              options = list(scrollX = TRUE)
              ) %>%
   formatStyle(
      'valid_filename',
      target = 'row',
      backgroundColor = styleEqual(c(0, 1), c('lightsalmon', 'white'))
   )
dt
```

```{r, child=c('versions.Rmd')}
```


