--- 
title: "Immcantation - enchantR"
subtitle: "File size tracker"
author: ""
date: "Updated: `r date()`"
knit: enchantr::render_book
site: bookdown::bookdown_site
documentclass: book
bibliography: "references.bib"
biblio-style: apalike
link-citations: yes
description: "enchantr file size tracker report"
output: enchantr::immcantation
params:
   input: 
      label: "`input`: Path a file of files, with paths to the log files."
      input: file
      value: "example-input.txt"
   metadata: 
      label: "`metadata`: Path to metadata."
      input: file
      value: !r NULL     
   output: 'tmp_input'
   outdir:
      label: '`outdir`: Output directory'
      input: text
      value: !r file.path(getwd(),'enchantr')
   date: 
      label: '`date`: Run date'
      input: date
      value: !r format(Sys.time(), "%Y-%m-%d")
   logo:
      label: "`logo`: Path to report logo"
      input: file
      value: !r file.path("assets", "logo.png")
   logolink:
      label: "`logolink`: URL to be added to the logo"
      input: text
      value: "immcantation.org"
   echo: 
      label: '`echo`: Show code in the report.'
      input: checkbox
      value: FALSE
   cache:
      label: '`cache`: Use cached results'
      input: checkbox
      value: FALSE
editor_options: 
  chunk_output_type: console
---

```{r global-options, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=4, fig.path = "figures/",
                      echo=params$echo,cache=params$cache,
                      warning=FALSE, message=FALSE,
                      out_dir=params$outdir,
                      eval.opts = c('eval', 'echo', 'fig.height', 'fig.width'))

suppressPackageStartupMessages(library("enchantr"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("tidyr"))
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("plotly"))

if (!dir.exists(params[['outdir']])) {
    dir.create(params[['outdir']], recursive = T)
}

file.copy(params$logo, 
          file.path(params$outdir,"assets", "logo.png"),
          recursive = T, overwrite=T)
```

# Input parameters

```{r input-parameters, results='asis'}
printParams(params)
```
```{r echo=FALSE, results='asis'}
print_table_caption(tag="input", text="Input parameters.")
save(params, file=file.path(params$outdir,"params.RData"))
```

## Log files loaded

```{r}
log_files <- read.delim(params[['input']], header=F)[[1]]
log_data <- readConsoleLogs(log_files)
```
```{r echo=FALSE, results='asis'}
for (x in sort(log_files)) {
   cat("* ", x, "\n")
}
```

```{r}
if (!is.null(params$metadata)) {
    metadata <- read.delim(params$metadata) %>%
        select(starts_with("filename"), sample_id) %>%
        pivot_longer(col=starts_with("filename")) %>%
        rename(filename=value) %>%
        mutate(filename=basename(filename)) %>%
        select(sample_id, filename)
} else {
    metadata <- data.frame(stringsAsFactors = F)
}
```

# Workflow

```{r, echo=FALSE,fig.width=8,fig.height=5}
log_data_graphs <- consoleLogsAsGraphs(log_data, metadata)
p_workflow <- plotWorkflow(log_data_graphs[["workflow"]])
p_workflow
```

```{r echo=F}
cat("\n\n")
```

# File processing 

```{r, results="asis", echo=FALSE, fig.width=8,fig.height=6}
ids <- names(log_data_graphs$by_sample)
for (i in order(ids)) {
    this_id <- ids[i]
    
    log_plot <- plotLogGraph(log_data_graphs$by_sample[[i]])
    
    # get node info from the graph
    plot_data <- log_plot$data

    # name is the vertex name, filename the original filename
    this_root_filename <- plot_data$filename[plot_data$is_input]
    this_root_name <- unique(plot_data$root_name)
    
    cat(paste0("## ",this_id,"\n\n"))
    cat("### Data flow \n\nNumber of sequences at each processing step of `", this_id,"`.", sep="")
    
    print(log_plot)
    
    plot_table <- cleanPlotData(plot_data)

    out_filename <- sub("\\.[^\\.]*$","",this_root_name)
    out_filename <- sub(": ", "_", out_filename)
    
    cat("\n\n### Barplot \n\n")
    caption <- paste0("Number of reads at different stages of the processing of ",this_id)
    tab <- eetable(plot_table, 
                   caption=caption,
                   outdir = params$outdir, 
                   file=out_filename)
    
    p <- ggplot(plot_table, 
           aes(x=filename, y=num_seqs, group=name)) +
        geom_bar(stat="identity") +
        theme_enchantr() +
        theme(
            axis.text.x = element_text(angle = 90, hjust=0.5, vjust=0)
        ) +
        labs(x="File", y="Number of sequences") # +
        # scale_x_discrete(labels= function(x) { gsub("(.*_)([^_]*$)","\\2",x)} ) # Do we need this for shorter x-axis labels?
        
    cat(tab$caption)
    p <- eeplot(p,outdir=params$outdir,
           file=strsplit(out_filename,"\\.")[[1]][1],
           caption="")
    print(p)
    cat(p$enchantr$html_caption)
    cat("\n\n")
}
```

# Final table

```{r, echo=F, results='asis'}
# Get log_data from the graphs. It has the metadata.
log_data <- graphDataFrame(log_data_graphs$workflow)
```

```{r fig.width=7, fig.height=4, fig.cap=caption}
# Extract task order from workflow plot
# p_workflow$data contains the node layout information with task names
ordered <- p_workflow$data %>%
    arrange(-y,x) %>%
    pull(name) %>%
    unique()

# Get unique tasks from log_data
log_tasks <- unique(log_data$task)

# Check if all tasks in log_data appear in the workflow plot
# Filter ordered to only include tasks that exist in log_data
ordered <- ordered[ordered %in% log_tasks]

# If there are tasks in log_data not in ordered, add them at the end
missing_tasks <- setdiff(log_tasks, ordered)
if (length(missing_tasks) > 0) {
    warning("Some tasks in log_data are not in the workflow plot: ", 
            paste(missing_tasks, collapse=", "))
    ordered <- c(ordered, missing_tasks)
}

log_data$task <- factor(log_data$task, levels=ordered , ordered = T)

id_col <- c("sample_id", "root_name")
id_col <- intersect(id_col, colnames(log_data))[1]

sequence_count_plot <- ggplot(log_data, aes(x=task, y=input_size, fill=!!rlang::sym(id_col))) +
    geom_bar(stat="identity", width=.5, position = "dodge") +
    scale_x_discrete(limits=ordered) +
    theme_enchantr() +
    theme(
        axis.text.x = element_text(angle = 90, hjust=0.5, vjust=0),
        legend.position = "bottom"
    ) +
    labs(x="Step", y="Number of sequences", fill="")

sequence_count_plot <- eeplot(sequence_count_plot,
                              outdir = params$outdir,
                              file="sequence_count_plot", 
                              caption = "Number of sequences at each processing step.")
caption <- sequence_count_plot$enchantr$html_caption
ggplotly(sequence_count_plot)
```

```{r echo=F, results='asis'}
tab <- eetable(log_data, caption="Table showing the number of sequences at each processing step. `is_input` indicates whether the file `input` is an input file that is at the root of the analysis process. `root_name` contains the filename of this root file, with the added text 'sample_id: ' in situations where the name is not unique..", outdir = params$outdir, file="log_data")
tab$table
```
```{r echo=FALSE,results='asis'}
print_table_caption(tag="log_data", text=tab$caption)
```


```{r, child=c('versions.Rmd')}
```

