--- 
title: "Immcantation - enchantR"
subtitle: "Find Threshold"
author: ""
date: "Updated: `r date()`"
knit: "bookdown::render_book"
site: bookdown::bookdown_site
documentclass: book
bibliography: "references.bib"
biblio-style: apalike
link-citations: yes
description: "enchantr single cell qc report"
output: enchantr::immcantation
params:
   input: 
      label: "`input`: Path to repertoires file"
      input: file
      value: "input.tsv"
   cloneby:
      label: "`cloneby`"
      input: text
      value: "sample_id"    
   singlecell:
      label: "`singlecell`"
      input: text
      value: "single_cell"          
   outname:
      label: "`outname`"
      input: text
      value: "find-threshold"
   nproc:
      label: "`nproc`"
      input: numeric
      value: 1      
   log:
      label: "`log`"
      input: text
      value: "command_log"
   outdir:
      label: '`outdir`: Output directory'
      input: text
      value: !r file.path(getwd(),'enchantr')
   date: 
      label: '`date`: Run date'
      input: date
      value: !r format(Sys.time(), "%Y-%m-%d")
   logo:
      label: "`logo`: Path to report logo"
      input: file
      value: !r file.path("assets", "logo.png")
   logolink:
      label: "`logolink`: URL to be added to the logo"
      input: text
      value: "immcantation.org"
   echo: 
      label: '`echo`: Show code in the report.'
      input: checkbox
      value: FALSE
   cache:
      label: '`cache`: Use cached results'
      input: checkbox
      value: FALSE
editor_options: 
  chunk_output_type: console
---

```{r global-options, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=4, fig.path = "figures/",
                      echo=params$echo,cache=params$cache,
                      warning=FALSE, message=FALSE,
                      eval.after="fig.cap",
                      out_dir=params$outdir,
                      eval.opts = c('eval', 'echo', 'fig.height', 'fig.width'))

# Libraries
suppressPackageStartupMessages(library("enchantr"))
suppressPackageStartupMessages(library("DT"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("airr"))
suppressPackageStartupMessages(library("alakazam"))
suppressPackageStartupMessages(library("shazam"))

file.copy(params$logo, 
          file.path(params$outdir,"assets", paste0("logo", gsub(".+(\\..+$)","\\1",params$logo))),
          recursive = T, overwrite=T)
```

# Input parameters


```{r input-parameters}
if (!dir.exists(params[['outdir']])) {
   dir.create(params[['outdir']], recursive = T)
}
printParams(params)
save(params, file=file.path(params$outdir,"params.RData"))
```

# Read repertoires


```{r}
# Read repertoires
db_files <- strsplit(params[['input']], ",")[[1]]

# Check input file
db <- bind_rows(lapply(db_files, function(x) {
    if (!file.exists(x)) {
        stop(paste0("File ", basename(x), " doesn't exist."))
    }
    read_rearrangement(x)
    }))



# db <- bind_rows(lapply(db_files, read_rearrangement))

input_size <- nrow(db)
is_heavy <- db[['locus']] %in% c("IGH", "TRB", "TRD")
bulk_heavy <- is_heavy & !db[[params$singlecell]]
sc_heavy <- is_heavy & db[[params$singlecell]]
bulk_dtn <- data.frame()
sc_dtn <- data.frame()

# Fix possible presence of bulk and single cell data
na_single <- is.na(db[[params$singlecell]])
if (length(na_single)>0) {
    db[[params$singlecell]][na_single] <- FALSE
}
db[[params$singlecell]] <- as.logical(db[[params$singlecell]])
```

# Distance to nearest

```{r sum_heavy_0, eval=sum(is_heavy)==0, echo=sum(is_heavy)==0, results='asis'}
cat("0 heavy chain sequences present. `distToNearest` requires heavy chain data. Setting `dist_neartest` to 'NA'")
db$dist_nearest <- NA
```

```{r distToNearest_bulk, eval=(any(db[[params$singlecell]] == F) && sum(bulk_heavy)>0) }
if (any(db[[params$singlecell]] == F) && sum(bulk_heavy)>0) {
    message("Using ",sum(bulk_heavy), " bulk heavy chain sequences.")
    bulk_dtn <- distToNearest(db[bulk_heavy,] , 
                               fields=params$cloneby,
                               sequenceColumn="junction", 
                               vCallColumn="v_call", jCallColumn="j_call",
                               model="ham", first=FALSE, VJthenLen=TRUE, normalize="len",
                               nproc=params$nproc)
    
    bulk_dtn <- distToNearest(bulk_dtn, 
                               fields=NULL,
                               cross=params$cloneby,
                               sequenceColumn="junction", 
                               vCallColumn="v_call", jCallColumn="j_call",
                               model="ham", first=FALSE, VJthenLen=TRUE, normalize="len",
                               nproc=params$nproc)
        
} 
```

```{r distToNearest_single, eval=(any(db[[params$singlecell]] == T) && sum(sc_heavy)>0) }
if (any(db[[params$singlecell]] == T) && sum(sc_heavy)>0) {
    message("Using ",sum(sc_heavy), " sc heavy chain sequences.")
    # Create unique sequence_id
    db[['cell_id']] <- paste0(db[['sample_id']],db[['cell_id']])
    sc_dtn <- distToNearest(db[sc_heavy,] , 
                          fields=params$cloneby,
                          sequenceColumn="junction", 
                          vCallColumn="v_call", jCallColumn="j_call",
                          model="ham", first=FALSE, VJthenLen=TRUE, normalize="len",
                          nproc=params$nproc,
                          cellIdColumn = "cell_id",
                          locusColumn = "locus",
                          onlyHeavy = TRUE)
    sc_dtn <- distToNearest(sc_dtn, 
                          cross=params$cloneby,
                          sequenceColumn="junction", 
                          vCallColumn="v_call", jCallColumn="j_call",
                          model="ham", first=FALSE, VJthenLen=TRUE, normalize="len",
                          nproc=params$nproc,
                          cellIdColumn = "cell_id",
                          locusColumn = "locus",
                          onlyHeavy = TRUE)    
} 
```

## Visualize distToNearest

```{r, fig.width=3*min(3,nrow(unique(db[,c("sample_id", params$singlecell)]))/3), fig.height=0.7*nrow(unique(db[,c("sample_id", params$singlecell)], drop=F))}
wrap_formula <- as.formula(paste0(params$singlecell,"~sample_id"))
db <- bind_rows(bulk_dtn,sc_dtn)
p <- ggplot(db) + 
    geom_histogram(aes(dist_nearest, fill=sample_id),binwidth = 0.01)

if ("cross_dist_nearest" %in% c(colnames(bulk_dtn),colnames(sc_dtn))) {
   
   if (any(!is.na(db[['cross_dist_nearest']]))) {
    p <- p + 
        geom_histogram(
            aes(x=cross_dist_nearest, y=-(..count..), fill=sample_id), 
            binwidth=0.01, position="identity") +
            scale_y_continuous(labels = abs)      
   } else {
      warning("All `cross_dist_nearest` values are NA.")
   }

}

p <- p +
    facet_wrap(wrap_formula, scales = "free_y", ncol=3, labeller = "label_both") +
    expand_limits(x = 0, y =0) %>%
    geom_vline(xintercept = 0.2, color="grey30", linetype="dotted")
p
```

# Find threshold


```{r, eval=all(is.na(db[['dist_nearest']]))}
# This chunk runs when all dist_nearest values are NA
threshold <- NA
threshold_summary <- data.frame(mean_threshold = NA)
```

```{r threshold, eval=!all(is.na(db[['dist_nearest']]))}
cross_dist_nearest <- NULL
if ("cross_dist_nearest" %in% colnames(db)) {
    if (any(!is.na(db[['cross_dist_nearest']]))) {
       cross_dist_nearest <- "cross_dist_nearest"
    } else {
       warning("All `cross_dist_nearest` values are NA.")
    }
}
threshold <- findThresholdDb(db, 
                            distanceColumn="dist_nearest", 
                            crossDistanceColumn=cross_dist_nearest,
                            method="gmm", 
                            model="gamma-norm",
                            edge = 0.9, subsample=NULL, 
                            cutoff = "user", spc = 0.995,
                            nproc=params$nproc, 
                            fields=params$cloneby)

threshold_summary <- gmmSummary(threshold) %>%
    mutate(mean_threshold=mean(threshold, na.rm=TRUE))
mean_threshold <- round(threshold_summary$mean_threshold[1],2)
eetable(threshold_summary, 
        paste0("Summary of threshold values. Mean threshold is: ", mean_threshold))  %>%
        DT::formatRound(columns=setdiff(colnames(threshold_summary)[-1],"model"),
                    digits=3)
```

```{r, eval=!all(is.na(db[['dist_nearest']])), results='asis'}
invisible(lapply(threshold, function(thr) {
   this_thr <- NA
   if (!is.null(attributes(thr$GmmThreshold))) {
      this_thr <- round(attributes(thr$GmmThreshold)$threshold,2)
   }
   cat ("\n\n## ",paste(c(thr[['fields']], ": ", this_thr),collapse=" "),"\n\n")
   print(thr[['plot']])
}))
```

# Save

```{r dbpass}
# pass <- db[['collapse_pass']]

if (!is.null(params$outname)) {
    output_fn <- paste0(params$outname,"_threshold-pass.tsv")
} else {
    output_fn <- sub(".tsv$", "_threshold-pass.tsv", basename(params$input))
}

if (!is.null(params$log)) {
    log_fn <- paste0(params$log,".txt")
} else {
    log_fn <- sub("_threshold-pass.tsv$", "_command_log.txt", basename(output_fn))
}

# write_rearrangement(db , file=output_fn)
write.table(threshold_summary, 
            sub("_threshold-pass.tsv$", "_threshold-summary.tsv" ,output_fn),
            quote=FALSE,sep="\t", row.names=FALSE)
cat(threshold_summary[['mean_threshold']][1], 
    file=sub("_threshold-pass.tsv$", "_threshold-mean.tsv" ,output_fn),
    append=F
)
```


```{r log}
cat("START> FindThreshold", file=log_fn, append=F)
cat(paste0("\nFILE> ",basename(params$input)), file=log_fn, append=T)
cat(paste0("\nOUTPUT> ",basename(output_fn)), file=log_fn, append=T)
cat(paste0("\nPASS> ",nrow(db)), file=log_fn, append=T)
cat(paste0("\nFAIL> ",input_size-nrow(db)), file=log_fn, append=T)
```


```{r, child=c('versions.Rmd')}
```