# Convergence

Run clonal detection combining all samples to identify overlapping "clones". The field
`convergent_clone_id` will be created.

```{r runconvergence, warning=TRUE}
if (!is.null(params$convergence_vgene)) {
    db <- db %>% filter(grepl(paste(params$convergence_vgene, collapse="|"), v_call))
}

if (sum(heavy_chains)>0) {
    if (params$model == "hierarchical") {
        if (all(db[[ singlecell ]] == T )) {
            cell_id <- 'cell_id'
        } else {
            cell_id <- NULL
            if (all(c(T,F) %in% db[[ singlecell ]])) {
                warning("Mix of single and bulk data. Setting cell_id=`NULL`.")
            }
        }
        db <- hierarchicalClones(db,
                                 threshold=params$convergence_threshold,
                                 method="aa",
                                 linkage=params$linkage,
                                 normalize="len",
                                 junction="junction",
                                 v_call="v_call", j_call="j_call",
                                 clone="convergent_clone_id",
                                 fields=NULL,
                                 cell_id=cell_id,
                                 locus="locus",
                                 only_heavy=TRUE,
                                 split_light=TRUE,
                                 first=FALSE,
                                 cdr3=FALSE, mod3=FALSE,
                                 max_n=0, nproc=params$nproc,
                                 verbose=FALSE, log=NULL,
                                 summarize_clones=FALSE)
    } else {
        stop("Unsuported model requested. Supported models: hierarchical")
    }
} else {
    warning("No heavy chain sequences found.")
    db$convergent_clone_id <- NA
}
```

## Heatmap

```{r overlap, eval="convergent_clone_id" %in% colnames(db)}
convergence_overlap <- plotDbOverlap(db %>% 
                                         filter(isHeavyChain(locus)) %>%
                                         rowwise() %>%
                                         mutate(clone_id = paste(
                                             unique(c(!!rlang::sym(params$cloneby), 
                                                      clone_id)), collapse ="_")
                                         ), 
                                     group="sample_id", 
                                     features=c("convergent_clone_id","clone_id"), 
                                     heatmap_colors=c("white","orange", "grey80"), 
                                     print_zero=FALSE, long_x_angle=90,
                                     title=NULL,xlab=NULL, ylab=NULL,
                                     plot_order="sample_id", 
                                     silent=T, similarity=c("min","min"),
                                     na.rm=FALSE, 
                                     identity=c('exact', 'exact'), 
                                     threshold=0,
                                     geom_text_size=3) 
```

```{r overlapconvergenceplot, fig.width=min(10,max(5,0.5*length(unique(db[['sample_id']])))),  fig.height=min(50,max(5,0.5*length(unique(db[['sample_id']])))), fig.cap=caption, eval=exists("convergence_overlap")}
caption <- paste0("Number of identical clone_id and convergent_clone_id. The percent represents the number of shared clones over the number of clones in the smaller set.")
overlapconvergenceplot <- convergence_overlap$p
overlapconvergenceplot <- eeplot(overlapconvergenceplot, 
       outdir=params$outdir, 
       file=knitr::opts_current$get('label'),
       caption=caption)
overlapconvergenceplot
caption <- overlapconvergenceplot$enchantr$html_caption
```

## UpSet plot

```{r upset, results='asis', eval="convergent_clone_id" %in% colnames(db)}
# Add clone_size
convergent_clone_sizes <- countClones(
            db %>% filter(isHeavyChain(locus)) %>% select(-clone_id), # Keep heavy chains only
            groups="sample_id",
            clone = "convergent_clone_id")
upset_plot <- plotConvergenceUpSet(convergent_clone_sizes)
if (is.null(upset_plot)) {
    cat("There aren't any convergent and expanded clones.")
    rm(upset_plot)
}
```


```{r upsetplot, fig.width=min(10,max(5,0.5*length(unique(db[['sample_id']])))),  fig.height=min(10,max(5,0.5*length(unique(db[['sample_id']])))), fig.cap=caption, eval=exists("upset_plot")}
caption <- paste0("Unique convergent_clone_id and clone_id overlap. Subset to expanded clones (size>1 in at least one sample). Show most shared top 31. (Note: 31 is the maximum set size in the R package ComplexHeatmap.")
us <- grid.grabExpr(draw(upset_plot)) 
upset_plot <- eeplot(us, 
       outdir=params$outdir, 
       file=knitr::opts_current$get('label'),
       caption=caption)
grid.draw(us)
caption <- upset_plot$enchantr$html_caption
```