# Convergence

Run clonal detection combining all samples to identify overlapping "clones". The field
`convergent_clone_id` will be created.

```{r, warning=TRUE}
if (sum(heavy_chains)>0) {
    if (params$model == "hierarchical") {
        if (all(db[[ params$singlecell ]] == T )) {
            cell_id <- 'cell_id'
        } else {
            cell_id <- NULL
            if (all(c(T,F) %in% db[[ params$singlecell ]])) {
                warning("Mix of single and bulk data. Setting cell_id=`NULL`.")
            }
        }
        db <- hierarchicalClones(db, 
                                 0.2, 
                                 method="aa",
                                 linkage=params$linkage, 
                                 normalize="len",
                                 junction="junction", 
                                 v_call="v_call", j_call="j_call", 
                                 clone="convergent_clone_id", 
                                 fields=NULL,
                                 cell_id=cell_id, 
                                 locus="locus", 
                                 only_heavy=TRUE, 
                                 split_light=TRUE,
                                 first=FALSE, 
                                 cdr3=FALSE, mod3=FALSE, 
                                 max_n=0, nproc=params$nproc,
                                 verbose=FALSE, log=NULL,
                                 summarize_clones=FALSE) 
    } else {
        stop("Unsuported model requested. Supported models: hierarchical")
    }
} else {
    warning("No heavy chain sequences found.")
    db$convergent_clone_id <- NA
}
```

```{r overlap}
convergence_overlap <- plotDbOverlap(db %>% 
                         filter(isHeavyChain(locus)), 
                         group="sample_id", 
                         features=c("convergent_clone_id","junction"), 
                         heatmap_colors=c("white","orange", "grey80"), 
                         print_zero=FALSE, long_x_angle=90,
                         title=NULL,xlab=NULL, ylab=NULL,
                         plot_order=c("tissue","sample_id"), 
                         silent=T, similarity=c("min","min"),
                         na.rm=FALSE, 
                         identity=c('exact', 'ham_nt'), 
                         threshold=round(params$threshold,3),
                         geom_text_size=3) 
```

```{r overlapconvergenceplot, fig.width=min(10,max(5,0.5*length(unique(db[['sample_id']])))),  fig.height=min(10,max(5,0.5*length(unique(db[['sample_id']])))), fig.cap=caption}
caption <- paste0("Number of identical convergent_clone_id and similar nt heavy chain junction unique sequences. Two sequences are similar if their nt hamming distance is <=",round(params$threshold,3), ". The percent represents the number of similar sequences over the number of sequences in the smaller set.")
overlapconvergenceplot <- convergence_overlap$p
overlapconvergenceplot <- eeplot(overlapconvergenceplot, 
       outdir=params$outdir, 
       file=knitr::opts_current$get('label'),
       caption=caption)
overlapconvergenceplot
caption <- overlapconvergenceplot$enchantr$html_caption
```