# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mutation_count <- function(germs, inputs, X = 0L, parallel = FALSE, return_count = FALSE) {
    .Call('_enchantr_mutation_count', PACKAGE = 'enchantr', germs, inputs, X, parallel, return_count)
}

