name: CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:

  unittest:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: immcantation/test:devel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sed -i '/test/ d' .Rbuildignore
          Rscript tests/setup/install_dep.R
      - name: Document
        run: |
          devtools::document()
        shell: Rscript {0}
      - name: Run Tests
        run: |
            testthat::test_local()
        shell: Rscript {0}
      - name: CRAN check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: |
              options(crayon.enabled=TRUE)
              rcmdcheck::rcmdcheck(
                args = c("--no-manual", 
                          "--no-tests", 
                          "--as-cran", 
                          "--run-donttest", 
                          "--timings"),
                error_on = "error", 
                check_dir = "check"
              )
        shell: Rscript {0}
      - name: Update container
        run: |
          curl -H "Content-Type:application/json" --data '{"docker_tag":"devel"}' -X POST https://hub.docker.com/api/build/v1/source/${{ secrets.DOCKERHUB_REPO }}/trigger/${{ secrets.DOCKERHUB_TRIGGER }}/call/
