name: Immcantation CI
# Run nf-core/airrflow with specified revision in
# immcantation/suite:devel after updating enchantr.
#
# This allows testing of a specific version of nf-core/airrflow 
# (branches, PRs, tags, commits) with immcantation/suite:devel
# (all immcantation tools in their devel version) and the 
# most recent changes in enchantr.
#
# Optionally, specific versions/commits of other immcantation
# packages (alakazam, shazam, scoper, dowser) can also be
# (re)installed prior to running nf-core/airrflow.
#
# Use cases:
#  - identify incoming issues for nf-core/airrflow
#  - unit testing of immcantation
#
# Revision examples:
# - dev (branch)
# - 4.3.1 (release tag)  
# - eb11e2e7e653e3353d3e3dbb687bb5d71b4990dc (commit SHA)
# - refs/pull/416/head (pull request - will clone and checkout PR)
on:
  workflow_dispatch:
    inputs:
      nfcore_revision:
        description: 'nf-core/airrflow revision. For PRs use: refs/pull/416/head'
        required: true
        default: 'dev'
        type: string
      alakazam_version:
        description: 'alakazam version/commit (leave empty to use container version)'
        required: false
        type: string
      shazam_version:
        description: 'shazam version/commit (leave empty to use container version)'
        required: false
        type: string
      scoper_version:
        description: 'scoper version/commit (leave empty to use container version)'
        required: false
        type: string
      dowser_version:
        description: 'dowser version/commit (leave empty to use container version)'
        required: false
        type: string

jobs:
  run-airrflow-immcantation:
    name: Run enchantr and nf-core/airrflow -r ${{ inputs.nfcore_revision }} in immcantation/suite:devel
    runs-on: ubuntu-latest
    container:
      image: immcantation/suite:devel
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Optional installation of Immcantation packages
        run: |
        
          # Install alakazam if version specified
          alakazam_version <- "${{ inputs.alakazam_version }}"
          if (nchar(alakazam_version) > 0) {
            cat("Installing alakazam from GitHub:", alakazam_version, "\n")
            devtools::install_github(
              "immcantation/alakazam", 
              ref=alakazam_version, 
              upgrade="never")
          }
          
          # Install shazam if version specified  
          shazam_version <- "${{ inputs.shazam_version }}"
          if (nchar(shazam_version) > 0) {
            cat("Installing shazam from GitHub:", shazam_version, "\n")
            devtools::install_github(
              "immcantation/shazam", 
              ref=shazam_version, 
              upgrade="never")
          }
          
          # Install scoper if version specified
          scoper_version <- "${{ inputs.scoper_version }}"
          if (nchar(scoper_version) > 0) {
            cat("Installing scoper from GitHub:", scoper_version, "\n")
            devtools::install_github(
              "immcantation/scoper", 
              ref=scoper_version,
              upgrade="never")
          }
          
          # Install dowser if version specified
          dowser_version <- "${{ inputs.dowser_version }}"
          if (nchar(dowser_version) > 0) {
            cat("Installing dowser from GitHub:", dowser_version, "\n")
            devtools::install_github(
              "immcantation/dowser",
              ref=dowser_version, 
              upgrade="never")
          }
        shell: Rscript {0}
      - name: Install enchantr
        run: |
          devtools::install(upgrade="never")
        shell: Rscript {0}
      - name: Set up airrflow environment
        run: |
          dnf install -y java-21-openjdk
          wget -qO- https://get.nextflow.io | bash && chmod +x nextflow
      - name: Clone nf-core/airrflow for PR testing (if needed)
        run: |
          if [[ "${{ inputs.nfcore_revision }}" == refs/pull/* ]]; then
            echo "Detected PR reference, cloning repository..."
            PR_NUMBER=$(echo "${{ inputs.nfcore_revision }}" | sed 's/refs\/pull\/\([0-9]*\)\/head/\1/')
            git clone https://github.com/nf-core/airrflow.git
            cd airrflow
            git fetch origin pull/$PR_NUMBER/head:pr-$PR_NUMBER
            git checkout pr-$PR_NUMBER
            echo "WORKFLOW_PATH=./airrflow" >> $GITHUB_ENV
            echo "REVISION_FLAG=" >> $GITHUB_ENV
          else
            echo "Using direct revision reference..."
            echo "WORKFLOW_PATH=nf-core/airrflow" >> $GITHUB_ENV
            echo "REVISION_FLAG=-r ${{ inputs.nfcore_revision }}" >> $GITHUB_ENV
          fi
      - name: Run nf-core/airrflow test command
        run: |
          ./nextflow run $WORKFLOW_PATH $REVISION_FLAG -profile test_assembled_hs -c .github/workflows/immcantation.config --outdir ./results