name: airrflow custom
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Nextflow workflow to run (e.g. nf-core/airrflow)'
        required: false
        default: 'nf-core/airrflow'
      branch:
        description: 'Branch of the workflow to run'
        required: false
        default: 'dev'

env:
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run workflow test with different profiles
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository
      == 'immcantation/enchantr') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - 24.10.5
          - latest-everything
        profile:
          [
            "test",
            "test_assembled_hs",
            "test_assembled_mm"
          ]
      fail-fast: false
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Check if Version.yaml changed
        uses: technote-space/get-diff-action@v4
        with:
          FILES: |
            docker/Version.yaml
      - name: Build new docker image
        if: env.MATCHED_FILES
        run: docker build --no-cache -t immcantation/enchantr:dev -f ./docker/Dockerfile .

      - name: Login to DockerHub
        if: env.MATCHED_FILES
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push new docker image
        if: env.MATCHED_FILES
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: immcantation/enchantr:dev

      - name: Build container with enchantr
        run: |
          docker build --no-cache -t immcantation/airrflow:dev -f ./docker/Dockerfile-enchantr ./docker

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data
        run: |
          nextflow run ${{ github.event.inputs.workflow }} -r ${{ github.event.inputs.branch }} -profile ${{ matrix.profile }},docker --outdir ./results -c .github/workflows/airrflow.config

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.profile }}
          path: |
            /home/runner/.nextflow.log
            /home/runner/work
            !/home/runner/work/conda
            !/home/runner/work/singularity
