name: Immcantation CI
# Run nf-core/airrflow with specified revision in
# immcantation/suite:devel after updating enchantr.
#
# This allows testing of a specific version of nf-core/airrflow 
# (branches, PRs, tags, commits) with immcantation/suite:devel
# (all immcantation tools in their devel version) and the 
# most recent changes in enchantr.
#
# Use cases:
#  - identify incoming issues for nf-core/airrflow
#  - unit testing of immcantation
#
# Revision examples:
# - dev (branch)
# - 4.3.1 (release tag)  
# - eb11e2e7e653e3353d3e3dbb687bb5d71b4990dc (commit SHA)
# - refs/pull/416/head (pull request - will clone and checkout PR)
on:
  workflow_dispatch:
    inputs:
      nfcore_revision:
        description: 'nf-core/airrflow revision. For PRs use: refs/pull/416/head'
        required: true
        default: 'dev'
        type: string

jobs:
  run-airrflow-immcantation:
    name: Run enchantr and nf-core/airrflow -r ${{ inputs.nfcore_revision }} in immcantation/suite:devel
    runs-on: ubuntu-latest
    container:
      image: immcantation/suite:devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install enchantr
        run: |
          devtools::install(upgrade="never")
        shell: Rscript {0}
      - name: Set up airrflow environment
        run: |
          dnf install -y java-21-openjdk
          wget -qO- https://get.nextflow.io | bash && chmod +x nextflow
      - name: Clone nf-core/airrflow for PR testing (if needed)
        run: |
          if [[ "${{ inputs.nfcore_revision }}" == refs/pull/* ]]; then
            echo "Detected PR reference, cloning repository..."
            PR_NUMBER=$(echo "${{ inputs.nfcore_revision }}" | sed 's/refs\/pull\/\([0-9]*\)\/head/\1/')
            git clone https://github.com/nf-core/airrflow.git
            cd airrflow
            git fetch origin pull/$PR_NUMBER/head:pr-$PR_NUMBER
            git checkout pr-$PR_NUMBER
            echo "WORKFLOW_PATH=./airrflow" >> $GITHUB_ENV
            echo "REVISION_FLAG=" >> $GITHUB_ENV
          else
            echo "Using direct revision reference..."
            echo "WORKFLOW_PATH=nf-core/airrflow" >> $GITHUB_ENV
            echo "REVISION_FLAG=-r ${{ inputs.nfcore_revision }}" >> $GITHUB_ENV
          fi
      - name: Run nf-core/airrflow test command
        run: |
          ./nextflow run $WORKFLOW_PATH $REVISION_FLAG -profile test_assembled_hs -c .github/workflows/immcantation.config --outdir ./results